export function main() {
    const titles = document.querySelectorAll('li.item');
    
    for( let i = 0; i < titles.length; i++ ){
        const
            item = titles[i],
            songTitle = item.querySelector('div.playdata__rate-list__song-info__name').innerText,
            diffValue = item.querySelector('div[class*="diff_icon"]').innerText,
            ratingValue = getRatingValue( songTitle, diffValue );
        
        if( ratingValue != '0.0' ){
            item.querySelector('div[class*="diff_icon"]').innerHTML = diffValue.replace( /[0-9+]{1,3}/, ratingValue );
            
            let
                yourScore = item.querySelector('div.playdata__rate-list__song-info__score').innerText.match(/[0-9]{1,7}/),
                htmlText = getInsertHtml(ratingValue, yourScore); 
            
            item.querySelector('div.playdata__rate-list__song-info__score').insertAdjacentHTML( 'beforebegin', htmlText );
        };
    };
};

function getInsertHtml( ratingValue, yourScore ) {
    const strength = getStrengthTable(),
    let yourStrength = 0;

    for( let i = 0; i < strength.length; i++ ){
        if( yourStrength == 0 ){
            if( strength[i][0] <= Number(yourScore) ) yourStrength = strength[i][1];
        };
    };

    const
        adjustedRating = ( yourStrength * ratingValue ).toFixed(2),
        paragStyle = '';
    
    if( yourStrength == 4 ) paragStyle = 'style="color:#ff0084"';
    
    return [
        '<div class="playdata__rate-list__song-info__score">',
            '<span class="song-score">RATE ' + yourStrength.toFixed(2) + 'x</span>',
            '<p ' + paragStyle + '>' + adjustedRating.toString() + '</p>',
        '</div>'
    ].join('');
};

// [ [ 0 プレイスコア, 1 倍率 ] ]
function getStrengthTable() {
    return [
        [990000, 4],
        [980000, 3.75],
        [970000, 3.5],
        [960000, 3.25],
        [950000, 3]
    ];
};

function getRatingValue( songTitle, diffValue ) {
    const rating = getRatingTable();
    
    for( let i = 0; i < rating.length; i++ ){
        if( rating[i][0] == songTitle ) {
            if( rating[i][1] == diffValue ) return rating[i][2].toFixed(1);
            if( rating[i][3] == diffValue ) return rating[i][4].toFixed(1);
        };
    };
};

// [ [ 0 曲名, 1 EXPERTレベル, 2 EXPERT定数, 3 INFERNOレベル, 4 INFERNO定数 ] ]
function getRatingTable() {
    return [
        ["叩ケ 叩ケ 手ェ叩ケ","EXPERT 12",12.3,"INFERNO ",],
        ["Fly to NEW WORLD","EXPERT 12",12.2,"INFERNO ",],
        ["透明声彩","EXPERT 11+",11.8,"INFERNO ",],
        ["うっせぇわ","EXPERT 12",12.2,"INFERNO ",],
        ["Fam☆Fam☆Time!","EXPERT 11+",11.9,"INFERNO ",],
        ["cœur","EXPERT 12+",12.7,"INFERNO ",],
        ["私はNo 1！","EXPERT 12",12.3,"INFERNO ",],
        ["ソロモン・ナイト","EXPERT 13",13.4,"INFERNO ",],
        ["LOVE!HUG!GROOVY!!","EXPERT 12",12.4,"INFERNO 13",13.5],
        ["Dig Delight!","EXPERT 11",11.4,"INFERNO ",],
        ["電乱★カウントダウン","EXPERT 12",12.5,"INFERNO ",],
        ["Photon Melodies","EXPERT 11",11.5,"INFERNO ",],
        ["ぐるぐるDJ TURN!!","EXPERT 12+",12.8,"INFERNO ",],
        ["sister's noise","EXPERT 10",10.1,"INFERNO ",],
        ["なだめスかし Negotiation","EXPERT 11+",11.9,"INFERNO ",],
        ["サクリファイス","EXPERT 12",12.2,"INFERNO ",],
        ["非実在系女子たちはどうすりゃいいですか？","EXPERT 12",12.6,"INFERNO ",],
        ["ぺこみこ大戦争！！","EXPERT 11",11.2,"INFERNO 13",13.2],
        ["Say!ファンファーレ!","EXPERT 12",12.5,"INFERNO ",],
        ["NEXT COLOR PLANET","EXPERT 12",12.6,"INFERNO ",],
        ["夢見る空へ","EXPERT 11",11.3,"INFERNO ",],
        ["お願いマッスル","EXPERT 10+",10.7,"INFERNO ",],
        ["マッチョアネーム？","EXPERT 12+",12.7,"INFERNO ",],
        ["HELLO to DREAM","EXPERT 9+",9.7,"INFERNO ",],
        ["over and over","EXPERT 10",10.4,"INFERNO ",],
        ["トロピカッ☆バケーション","EXPERT 10+",10.7,"INFERNO ",],
        ["秒針を噛む","EXPERT 11",11.0,"INFERNO ",],
        ["ないものねだり","EXPERT 11",11.1,"INFERNO ",],
        ["HOT LIMIT","EXPERT 10",10.0,"INFERNO ",],
        ["キラメキライダー☆","EXPERT 11",11.5,"INFERNO ",],
        ["ガヴリールドロップキック","EXPERT 11",11.0,"INFERNO ",],
        ["This game","EXPERT 10+",10.7,"INFERNO ",],
        ["RAGE OF DUST","EXPERT 9",9.6,"INFERNO ",],
        ["Make it！","EXPERT 9",9.4,"INFERNO ",],
        ["Make it！ (DJ Genki Remix)","EXPERT 11",11.6,"INFERNO ",],
        ["キラッとスタート","EXPERT 10",10.2,"INFERNO ",],
        ["キラッとスタート (USAO Remix)","EXPERT 12",12.5,"INFERNO ",],
        ["ハート♥イロ♥トリドリ〜ム","EXPERT 10",10.1,"INFERNO ",],
        ["ダダダダ天使","EXPERT 12",12.0,"INFERNO ",],
        ["青空のラプソディ","EXPERT 9",9.3,"INFERNO ",],
        ["Bravely You","EXPERT 9",9.5,"INFERNO ",],
        ["ぼなぺてぃーと♡S","EXPERT 11",11.5,"INFERNO ",],
        ["デタラメなマイナスとプラスにおけるブレンド考","EXPERT 10",10.0,"INFERNO ",],
        ["輪廻転生","EXPERT 12",12.3,"INFERNO ",],
        ["ストライク・ザ・ブラッド","EXPERT 11+",11.7,"INFERNO ",],
        ["新宝島","EXPERT 9",9.4,"INFERNO ",],
        ["U.S.A.","EXPERT 10",10.2,"INFERNO ",],
        ["Shiny Smily Story","EXPERT 10",10.4,"INFERNO ",],
        ["Dream☆Story","EXPERT 11",11.2,"INFERNO ",],
        ["without U","EXPERT 10",10.2,"INFERNO ",],
        ["シャルル","EXPERT 10",10.3,"INFERNO ",],
        ["ドラマツルギー","EXPERT 10",10.1,"INFERNO ",],
        ["オドループ","EXPERT 10",10.4,"INFERNO ",],
        ["only my railgun","EXPERT 9",9.5,"INFERNO ",],
        ["You Only Live Once","EXPERT 9",9.1,"INFERNO ",],
        ["残酷な天使のテーゼ","EXPERT 9",9.3,"INFERNO ",],
        ["ただ君に晴れ","EXPERT 9",9.6,"INFERNO ",],
        ["The Light","EXPERT 12",12.1,"INFERNO ",],
        ["AIAIAI (feat. 中田ヤスタカ)","EXPERT 9",9.4,"INFERNO ",],
        ["Hello, Morning","EXPERT 11",11.2,"INFERNO ",],
        ["Raise Your Heart!!","EXPERT 10",10.6,"INFERNO ",],
        ["SHINY DAYS","EXPERT 9",9.0,"INFERNO ",],
        ["EXCITE","EXPERT 10",10.0,"INFERNO ",],
        ["シュガーソングとビターステップ","EXPERT 10",10.4,"INFERNO ",],
        ["ファティマ","EXPERT 9",9.5,"INFERNO ",],
        ["回レ！雪月花","EXPERT 11",11.0,"INFERNO ",],
        ["ピースサイン","EXPERT 9+",9.8,"INFERNO ",],
        ["徒花ネクロマンシー","EXPERT 9+",9.7,"INFERNO ",],
        ["ようこそジャパリパークへ","EXPERT 10+",10.7,"INFERNO ",],
        ["POP TEAM EPIC","EXPERT 11",11.4,"INFERNO ",],
        ["ファッとして桃源郷","EXPERT 12",12.0,"INFERNO ",],
        ["Nameless Story","EXPERT 10",10.3,"INFERNO ",],
        ["TOMORROW","EXPERT 10",10.4,"INFERNO ",],
        ["五等分の気持ち","EXPERT 9+",9.9,"INFERNO ",],
        ["ギミチョコ!!","EXPERT 12+",12.9,"INFERNO ",],
        ["ウマーベラス","EXPERT 9+",9.8,"INFERNO ",],
        ["KING","EXPERT 11",11.6,"INFERNO ",],
        ["ダーリンダンス","EXPERT 12+",12.8,"INFERNO ",],
        ["トリノコシティ","EXPERT 12",12.2,"INFERNO ",],
        ["サマータイムレコード","EXPERT 11+",11.9,"INFERNO ",],
        ["テレキャスタービーボーイ","EXPERT 11+",11.9,"INFERNO ",],
        ["フィクサー","EXPERT 12+",12.9,"INFERNO ",],
        ["バレリーコ","EXPERT 11",11.6,"INFERNO ",],
        ["だれかの心臓になれたなら","EXPERT 12",12.1,"INFERNO ",],
        ["六兆年と一夜物語","EXPERT 12",12.5,"INFERNO ",],
        ["ワールドイズマイン","EXPERT 11",11.6,"INFERNO ",],
        ["進捗どうですか！","EXPERT 12+",12.8,"INFERNO ",],
        ["ぼくらの16bit戦争","EXPERT 13",13.4,"INFERNO ",],
        ["隔絶≡タナトス","EXPERT 13",13.5,"INFERNO ",],
        ["アスノヨゾラ哨戒班","EXPERT 11+",11.9,"INFERNO ",],
        ["ヒビカセ","EXPERT 12",12.3,"INFERNO ",],
        ["脳漿炸裂ガール","EXPERT 13",13.5,"INFERNO ",],
        ["ポジティブ☆ダンスタイム","EXPERT 11",11.6,"INFERNO ",],
        ["Gimme×Gimme feat. 初音ミク・鏡音リン","EXPERT 12",12.0,"INFERNO ",],
        ["39みゅーじっく！","EXPERT 10+",10.9,"INFERNO ",],
        ["ブリキノダンス","EXPERT 12",12.3,"INFERNO ",],
        ["チュルリラ・チュルリラ・ダッダッダ！","EXPERT 12",12.4,"INFERNO ",],
        ["おばけのウケねらい","EXPERT 11+",11.7,"INFERNO ",],
        ["ベノム","EXPERT 12",12.1,"INFERNO ",],
        ["リアル初音ミクの消失","EXPERT 13+",13.7,"INFERNO ",],
        ["セツナトリップ","EXPERT 12",12.1,"INFERNO ",],
        ["カゲロウデイズ","EXPERT 11",11.3,"INFERNO ",],
        ["天ノ弱","EXPERT 10",10.1,"INFERNO ",],
        ["ゴーストルール","EXPERT 11",11.6,"INFERNO ",],
        ["ロストワンの号哭","EXPERT 12",12.2,"INFERNO ",],
        ["いーあるふぁんくらぶ","EXPERT 10",10.0,"INFERNO ",],
        ["初音ミクの消失","EXPERT 13+",13.8,"INFERNO ",],
        ["劣等上等","EXPERT 11+",11.9,"INFERNO ",],
        ["アカリがやってきたぞっ","EXPERT 11",11.2,"INFERNO ",],
        ["太陽系デスコ","EXPERT 10+",10.7,"INFERNO ",],
        ["気まぐれメルシィ feat. 初音ミク","EXPERT 10",10.5,"INFERNO ",],
        ["幸せになれる隠しコマンドがあるらしい","EXPERT 13",13.3,"INFERNO ",],
        ["千本桜","EXPERT 10",10.4,"INFERNO ",],
        ["エイリアンエイリアン","EXPERT 10",10.5,"INFERNO ",],
        ["砂の惑星 feat. 初音ミク","EXPERT 10",10.5,"INFERNO ",],
        ["マトリョシカ","EXPERT 10",10.4,"INFERNO ",],
        ["Seyana. ～何でも言うことを聞いてくれるアカネチャン～","EXPERT 11+",11.7,"INFERNO ",],
        ["フラジール","EXPERT 10",10.3,"INFERNO ",],
        ["ロキ","EXPERT 11",11.6,"INFERNO ",],
        ["ウミユリ海底譚","EXPERT 10",10.2,"INFERNO ",],
        ["スクランブル交際","EXPERT 11",11.0,"INFERNO ",],
        ["乙女解剖","EXPERT 9",9.2,"INFERNO ",],
        ["Crime Wave","EXPERT 12+",12.7,"INFERNO ",],
        ["チルノは覚醒サマーデイズ！","EXPERT 12",12.3,"INFERNO ",],
        ["エピクロスの虹はもう見えない","EXPERT 11",11.3,"INFERNO ",],
        ["ARROW RAIN feat.ayame","EXPERT 12",12.6,"INFERNO ",],
        ["四次元跳躍機関","EXPERT 12+",12.7,"INFERNO ",],
        ["Destructive Little Sister","EXPERT 13+",13.9,"INFERNO ",],
        ["物凄い勢いでけーねが物凄いうた","EXPERT 12",12.2,"INFERNO ",],
        ["患部で止まってすぐ溶ける ～ 狂気の優曇華院","EXPERT 13",13.2,"INFERNO ",],
        ["Scream out!","EXPERT 12+",12.8,"INFERNO ",],
        ["ホイホイ☆幻想ホロイズム","EXPERT 12+",12.7,"INFERNO ",],
        ["Help me, ERINNNNNN!!","EXPERT 11",11.6,"INFERNO ",],
        ["進捗どうですか？","EXPERT 12",12.5,"INFERNO ",],
        ["Sweet Requiem","EXPERT 12+",12.7,"INFERNO ",],
        ["明星ロケット","EXPERT 11+",11.7,"INFERNO ",],
        ["ゆけむり魂温泉 II","EXPERT 12",12.0,"INFERNO ",],
        ["Calamity Fortune","EXPERT 13+",13.7,"INFERNO ",],
        ["ケロ⑨Destiny","EXPERT 11+",11.7,"INFERNO ",],
        ["風に乗せた願い","EXPERT 10",10.3,"INFERNO ",],
        ["LOVE EAST","EXPERT 11",11.0,"INFERNO ",],
        ["天狗の落とし文 feat. ytr","EXPERT 12",12.1,"INFERNO ",],
        ["神寂","EXPERT 13",13.5,"INFERNO ",],
        ["悪戯センセーション","EXPERT 12",12.3,"INFERNO ",],
        ["ナイト・オブ・ナイツ (かめりあ’s“ワンス・アポン・ア・ナイト”Remix)","EXPERT 13",13.1,"INFERNO ",],
        ["Mami Mami Zone","EXPERT 11",11.4,"INFERNO ",],
        ["チルノのパーフェクトさんすう教室","EXPERT 11",11.5,"INFERNO ",],
        ["待チ人ハ来ズ。","EXPERT 10",10.5,"INFERNO ",],
        ["taboo tears you up 2017","EXPERT 12",12.4,"INFERNO ",],
        ["Bad Apple!! feat. nomico","EXPERT 9",9.3,"INFERNO ",],
        ["ナイト・オブ・ナイツ","EXPERT 12",12.0,"INFERNO ",],
        ["WARNING×WARNING×WARNING","EXPERT 11",11.5,"INFERNO ",],
        ["シャカリキ・ファイト・ブンブン","EXPERT 11+",11.7,"INFERNO ",],
        ["ニュー・ウェーブ","EXPERT 9",9.3,"INFERNO ",],
        ["ガンガン・ドンドン","EXPERT 9+",9.7,"INFERNO ",],
        ["スマイル・アンド・ティアズ","EXPERT 9",9.5,"INFERNO ",],
        ["STILL HOT IN MY HEART","EXPERT 10",10.3,"INFERNO ",],
        ["Over the sweat and tears","EXPERT 9",9.4,"INFERNO ",],
        ["Singin'☆Shine！","EXPERT 9",9.6,"INFERNO ",],
        ["Avant Raze","EXPERT 12",12.6,"INFERNO ",],
        ["#1f1e33","EXPERT 13+",13.9,"INFERNO ",],
        ["Arcahv","EXPERT 13",13.6,"INFERNO ",],
        ["最強STRONGER","EXPERT 14",14.0,"INFERNO ",],
        ["Let you DIVE! (nitro rmx)","EXPERT 12+",12.8,"INFERNO ",],
        ["Sheriruth (Laur Remix)","EXPERT 13",13.3,"INFERNO ",],
        ["さんさーら！","EXPERT 12",12.4,"INFERNO ",],
        ["Night Club Junkie","EXPERT 12",12.5,"INFERNO ",],
        ["PUPA","EXPERT 13+",13.7,"INFERNO ",],
        ["Destr0yer","EXPERT 13",13.0,"INFERNO ",],
        ["もぺもぺ","EXPERT 12+",12.7,"INFERNO ",],
        ["MAGENTA POTION","EXPERT 12",12.6,"INFERNO ",],
        ["進捗WARS feat．ビートまりお","EXPERT 11",11.5,"INFERNO ",],
        ["Apocalypse","EXPERT 12",12.4,"INFERNO ",],
        ["You are the Miserable","EXPERT 13+",13.9,"INFERNO ",],
        ["Stasis","EXPERT 13",13.6,"INFERNO ",],
        ["Rainmaker","EXPERT 13",13.5,"INFERNO ",],
        ["Weg","EXPERT 12",12.3,"INFERNO ",],
        ["From Zero feat. 利香","EXPERT 11+",11.8,"INFERNO ",],
        ["PRESS START!","EXPERT 12+",12.7,"INFERNO ",],
        ["TWISTSTEP","EXPERT 12+",12.7,"INFERNO ",],
        ["Future Cαndy","EXPERT 12+",12.7,"INFERNO ",],
        ["Fish Fight!","EXPERT 11",11.6,"INFERNO ",],
        ["THERAPY","EXPERT 12+",12.7,"INFERNO ",],
        ["グルーヴ・ザ・ハート","EXPERT 12",12.5,"INFERNO ",],
        ["Got more raves?","EXPERT 13",13.5,"INFERNO ",],
        ["Good Night, Bad Luck.","EXPERT 13+",13.7,"INFERNO ",],
        ["Grayed Out-Antifront-","EXPERT 13",13.2,"INFERNO ",],
        ["インドア系ならトラックメイカー","EXPERT 12+",12.9,"INFERNO ",],
        ["ダンシング☆サムライ","EXPERT 10",10.5,"INFERNO ",],
        ["WHITE","EXPERT 10",10.5,"INFERNO ",],
        ["Brain Power","EXPERT 13",13.0,"INFERNO ",],
        ["聖者の鼓動","EXPERT 12",12.4,"INFERNO ",],
        ["BUCHiGiRE Berserker","EXPERT 13+",13.9,"INFERNO ",],
        ["君のStarlight Road","EXPERT 10",10.3,"INFERNO ",],
        ["FUJIN Rumble","EXPERT 13",13.6,"INFERNO ",],
        ["Eyes on me feat. Such","EXPERT 12",12.4,"INFERNO ",],
        ["GOODWORLD","EXPERT 12",12.6,"INFERNO ",],
        ["Altale","EXPERT 12",12.3,"INFERNO ",],
        ["ベースラインやってる？笑","EXPERT 12",12.2,"INFERNO ",],
        ["EU over Progress","EXPERT 12+",12.7,"INFERNO ",],
        ["燐廻","EXPERT 11",11.1,"INFERNO ",],
        ["『エキセントリック少年ボウイ』のテーマ","EXPERT 12",12.6,"INFERNO ",],
        ["Jägermeister","EXPERT 11",11.2,"INFERNO ",],
        ["What's this?","EXPERT 10",10.2,"INFERNO ",],
        ["FREEDOM DiVE↓","EXPERT 13+",13.9,"INFERNO ",],
        ["Honey Panic!","EXPERT 12",12.0,"INFERNO ",],
        ["Pixel Galaxy","EXPERT 10+",10.8,"INFERNO ",],
        ["集結の華々","EXPERT 10+",10.9,"INFERNO ",],
        ["conflict","EXPERT 13",13.4,"INFERNO ",],
        ["こんにちは、ARuFaです。","EXPERT 10",10.4,"INFERNO ",],
        ["ぼくの夢、メチャクソ無限湧き","EXPERT 12",12.6,"INFERNO 13+",13.8],
        ["ゲームオーバー (feat. TORIENA)","EXPERT 11+",11.7,"INFERNO ",],
        ["ルーンファクトリー４スペシャルより「この想いを乗せて」","EXPERT 9",9.0,"INFERNO ",],
        ["Ouvertüre","EXPERT 13",13.3,"INFERNO ",],
        ["Love Kills U","EXPERT 12",12.5,"INFERNO ",],
        ["Kira☆Kira☆Night","EXPERT 12+",12.9,"INFERNO ",],
        ["YOG","EXPERT 13+",13.8,"INFERNO ",],
        ["Lost Illusion","EXPERT 12+",12.7,"INFERNO ",],
        ["Cauliflower","EXPERT 12+",12.8,"INFERNO ",],
        ["Purple Skies","EXPERT 12",12.4,"INFERNO ",],
        ["Lhaksha","EXPERT 12",12.5,"INFERNO ",],
        ["LIN NE KRO NE feat. lasah","EXPERT 13+",13.7,"INFERNO ",],
        ["フリーフォール","EXPERT 12+",12.7,"INFERNO ",],
        ["猫娘","EXPERT 13+",13.7,"INFERNO ",],
        ["QiXiN MAdN3ss 2153","EXPERT 13+",13.9,"INFERNO ",],
        ["ARTEMiS","EXPERT 13+",13.9,"INFERNO ",],
        ["with U","EXPERT 11+",11.8,"INFERNO 13",13.6],
        ["Tell Me","EXPERT 11+",11.8,"INFERNO ",],
        ["LETHAL;WEAPON","EXPERT 12+",12.9,"INFERNO ",],
        ["THE MUZZLE FACING","EXPERT 13+",13.8,"INFERNO ",],
        ["GASHATT","EXPERT 12",12.4,"INFERNO ",],
        ["Demon's Rave","EXPERT 12+",12.8,"INFERNO ",],
        ["jacaranda","EXPERT 12+",12.7,"INFERNO ",],
        ["CHECKER FLAG","EXPERT 12+",12.9,"INFERNO ",],
        ["Stratoliner","EXPERT 12+",12.8,"INFERNO ",],
        ["Utopia feat. shully","EXPERT 12",12.6,"INFERNO ",],
        ["Let you DIVE!","EXPERT 11+",11.8,"INFERNO 13",13.4],
        ["Machinery of Avoid","EXPERT 12+",12.7,"INFERNO ",],
        ["Datamania (tpz Overheat Remix)","EXPERT 12",12.6,"INFERNO ",],
        ["超MANJIラッシュ","EXPERT 13+",13.7,"INFERNO ",],
        ["Meta-Mysteria","EXPERT 14",14.1,"INFERNO ",],
        ["Eternal Ending","EXPERT 13",13.4,"INFERNO ",],
        ["EVE","EXPERT 13",13.1,"INFERNO ",],
        ["eden","EXPERT 13",13.3,"INFERNO 14",14.1],
        ["Silentphobia","EXPERT 13",13.6,"INFERNO 14",14.1],
        ["やけにインザレイン feat. 小林私","EXPERT 13",13.1,"INFERNO ",],
        ["Traveller feat.moimoi","EXPERT 12",12.4,"INFERNO ",],
        ["FLVSH OUT","EXPERT 13",13.5,"INFERNO ",],
        ["BSCS","EXPERT 13",13.3,"INFERNO ",],
        ["Popping Happiness!","EXPERT 12",12.4,"INFERNO ",],
        ["Madwing","EXPERT 12+",12.8,"INFERNO ",],
        ["TRICKL4SH 220","EXPERT 13+",13.8,"INFERNO ",],
        ["SHAKE!","EXPERT 12+",12.7,"INFERNO ",],
        ["DUAL BREAKER XX","EXPERT 13+",13.8,"INFERNO ",],
        ["Megaton Killer","EXPERT 13",13.6,"INFERNO ",],
        ["ATAMA WARUI","EXPERT 12+",12.9,"INFERNO ",],
        ["Liberate","EXPERT 13",13.1,"INFERNO ",],
        ["Animosity","EXPERT 13+",13.8,"INFERNO ",],
        ["Big Bang","EXPERT 14",14.0,"INFERNO ",],
        ["恋メタル","EXPERT 12+",12.7,"INFERNO ",],
        ["はげしこの夜 -Psylent Crazy Night-","EXPERT 13+",13.7,"INFERNO ",],
        ["パニックポップ☆フェスティバル!!!","EXPERT 13",13.3,"INFERNO ",],
        ["Stasis feat.motoko -WACCA EDiT-","EXPERT 12+",12.7,"INFERNO ",],
        ["RAV#GIRL","EXPERT 12",12.6,"INFERNO ",],
        ["KALACAKLA","EXPERT 12+",12.7,"INFERNO ",],
        ["Poppin' Shower","EXPERT 12",12.5,"INFERNO ",],
        ["While Shining feat.Yukacco","EXPERT 12",12.3,"INFERNO ",],
        ["ALiVE","EXPERT 11",11.0,"INFERNO ",],
        ["ONOMATO Pairing!!!","EXPERT 12",12.4,"INFERNO ",],
        ["SUPER REACTOR","EXPERT 13",13.0,"INFERNO ",],
        ["GENOCIDER","EXPERT 14",14.1,"INFERNO ",],
        ["ツアー・ファイナル","EXPERT 12",12.3,"INFERNO ",],
        ["Metamorphose","EXPERT 12+",12.7,"INFERNO ",],
        ["MAGiC4LG1RL M3GA S7R1KE!","EXPERT 13",13.1,"INFERNO ",],
        ["METEOR BURST","EXPERT 13+",13.8,"INFERNO ",],
        ["XTREME","EXPERT 12+",12.9,"INFERNO 14",14.0],
        ["天使光輪","EXPERT 13",13.2,"INFERNO 14",14.1],
        ["Ultra Red","EXPERT 12+",12.8,"INFERNO ",],
        ["サイクルヒット","EXPERT 13",13.5,"INFERNO ",],
        ["Strange Bar","EXPERT 12+",12.8,"INFERNO ",],
        ["Murasaki","EXPERT 12",12.4,"INFERNO ",],
        ["Mazy Metroplex","EXPERT 13+",13.7,"INFERNO ",],
        ["LOSE CONTROL","EXPERT 11",11.3,"INFERNO ",],
        ["†DOOF†SENC†","EXPERT 13",13.6,"INFERNO ",],
        ["Shiny Memory feat.Yukacco","EXPERT 12",12.5,"INFERNO ",],
        ["BLVST BEVT","EXPERT 12",12.6,"INFERNO ",],
        ["JINGLE DEATH","EXPERT 13",13.2,"INFERNO ",],
        ["Invisible Frenzy","EXPERT 14",14.0,"INFERNO ",],
        ["VOX Diamond","EXPERT 12",12.6,"INFERNO ",],
        ["Chariot","EXPERT 12",12.4,"INFERNO ",],
        ["Akareram","EXPERT 11+",11.7,"INFERNO ",],
        ["Galaxy Friends","EXPERT 12+",12.7,"INFERNO ",],
        ["13 Donkeys","EXPERT 12",12.2,"INFERNO ",],
        ["ADAM","EXPERT 13",13.4,"INFERNO ",],
        ["ATARAX1A","EXPERT 12",12.5,"INFERNO ",],
        ["HiGHER","EXPERT 12",12.2,"INFERNO ",],
        ["Source of Creation","EXPERT 11",11.3,"INFERNO ",],
        ["Exitium","EXPERT 14",14.1,"INFERNO ",],
        ["Blaze","EXPERT 11+",11.7,"INFERNO ",],
        ["GRiDGALAXY","EXPERT 11",11.5,"INFERNO ",],
        ["Jingle","EXPERT 11",11.3,"INFERNO ",],
        ["BATTLE NO.1","EXPERT 13+",13.7,"INFERNO ",],
        ["LEVATEiN feat. 野宮あゆみ","EXPERT 12",12.5,"INFERNO ",],
        ["BIG HEAD BANGING","EXPERT 13+",13.8,"INFERNO ",],
        ["Knight Rider","EXPERT 13",13.3,"INFERNO ",],
        ["PARALLEL★PRISM","EXPERT 10",10.1,"INFERNO ",],
        ["Rainbow Dream","EXPERT 11",11.4,"INFERNO ",],
        ["Quon","EXPERT 12+",12.8,"INFERNO 13+",13.9],
        ["Poseidon","EXPERT 13+",13.8,"INFERNO ",],
        ["HELL FLAME","EXPERT 12+",12.7,"INFERNO 13+",13.9],
        ["Gate One","EXPERT 12",12.0,"INFERNO ",],
        ["Over My Hand","EXPERT 11",11.1,"INFERNO ",],
        ["Are You Ready","EXPERT 12",12.5,"INFERNO ",],
        ["MEMORiZE","EXPERT 10",10.0,"INFERNO ",],
        ["illanai-assorted","EXPERT 12+",12.9,"INFERNO ",],
        ["Sunshine","EXPERT 11",11.3,"INFERNO ",],
        ["BOOM! BOOM!! BOOM!!!","EXPERT 12",12.3,"INFERNO ",],
        ["Ever Free(Raw Edit)","EXPERT 10",10.1,"INFERNO ",],
        ["Try again","EXPERT 10",10.6,"INFERNO ",],
        ["BLUE SKY feat. 野宮あゆみ","EXPERT 10",10.4,"INFERNO ",],
        ["Sound Chimera","EXPERT 12+",12.8,"INFERNO 13+",13.9],
        ["Soldiers","EXPERT 11+",11.9,"INFERNO ",],
        ["Fight for the CORE feat. Daisuke","EXPERT 12",12.6,"INFERNO ",],
        ["Shining Harmony","EXPERT 12",12.2,"INFERNO ",]
    ];
};
